# Generated by Django 4.2 on 2023-06-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
