# Generated by Django 4.2 on 2023-06-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
